apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: hello-express
build:
  artifacts:
  - image: node-example
    context: docker
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
